/* -*- buffer-read-only:t -*-
   This file is automatically generated. Do not edit! */
#ifndef SP_RESNAME
#define SP_RESNAME python
#endif /* SP_RESNAME */
#if !SPDLL
#ifndef SP_STATIC_FOREIGN_RESOURCE
/* 3.9 If not SPDLL then this is a static foreign resource */
#define SP_STATIC_FOREIGN_RESOURCE 1
#endif /* SP_STATIC_FOREIGN_RESOURCE */
#endif /* !SPDLL */

#include <sicstus/sicstus.h>
#include <stdlib.h>

#if ((SP_DYNAMIC_FOREIGN_RESOURCE || SPDLL) && !MULTI_SP_AWARE)
#ifndef sp_GlobalSICStus
#define sp_GlobalSICStus SP_RESNAME_CATENATE(sp_GlobalSICStus,SP_RESNAME)
#endif /* sp_GlobalSICStus */
extern SICSTUS_API_STRUCT_TYPE *sp_GlobalSICStus; /* name mangled */
#endif /* ((SP_DYNAMIC_FOREIGN_RESOURCE || SPDLL) && !MULTI_SP_AWARE) */
#define GLUE_python 1
#ifndef GLUEDEFS
#define GLUEDEFS 1
#define GlueErr(ArgNo,Exp,Culprit) {glue_argno=(ArgNo);glue_exp=(Exp);glue_culprit=(Culprit);goto glue_err;}
#define GlueTestExcp if (!glue_flidata->excp_flag) {glue_retval=0; glue_flidata->excp_flag=1;}
#define GlueSkipArgsOnExcp if (!glue_flidata->excp_flag) {goto glue_way_out;}else{}
#if SP_FOREIGN_SPENV || 1 /* 3.9 always on */
#define GlueArgdecl SPEnv *spenv
#define GetGlueAPIDispatch() (spenv)
#define GetGlueFLIData() *(spenv->fli_data)
#elif SP_FOREIGN_STASH
#define GlueArgdecl struct worker *w, void* *pstash
#define GetGlueFLIData() *(struct sp_fli_info **)w
#else /* !SP_FOREIGN_STASH */
#define GlueArgdecl struct worker *w
#define GetGlueFLIData() *(struct sp_fli_info **)w
#endif /* !SP_FOREIGN_STASH */
#define GlueX(I) glue_flidata->term[I]
#define GlueRefTerm(Ref) (glue_flidata->fli_stack_start[Ref])
#endif /* !SP_FOREIGN_STASH */

/* used for serializing access from multiple sicstus runtimes, even if !MULTI_SP_AWARE */
static SP_mutex sp_resource_mutex_python=SP_MUTEX_INITIALIZER;
#if SP_STATIC_FOREIGN_RESOURCE
#undef SP_SINGLE_THREADED
#endif /* SP_STATIC_FOREIGN_RESOURCE */
/* used for detecting rentrancy nesting. 1 when in the foreign
   resource unless recursive call from foreign resource through, e.g.,
   SP_query back to foreign resource. */
#if SP_SINGLE_THREADED
static int sp_resource_nesting_python=0;
#endif /* SP_SINGLE_THREADED */
static int SPCDECL python_init_stub(GlueArgdecl, int when);
static int SPCDECL python_deinit_stub(GlueArgdecl, int when);
#ifndef SPFUNCVARS
#define SPFUNCVARS 1
/* Using 3.9 API (dispatch based) */
#include <stdio.h>
#include <sicstus/spaux.c> /* defines sp_main_helper() etc */
#endif /* SPFUNCVARS */

#ifdef __cplusplus
extern "C" {
#endif

/* 3.9 Mangle the name for link-time checking of MULTI_SP_AWARE-ness etc */
#ifdef SP_MANGLE
#define init SP_MANGLE(init)
#endif /* SP_MANGLE */
extern void SPCDECL init PROTOTYPE((SPAPI_ARG_PROTO_DECL int));
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SP_MANGLE
#define deinit SP_MANGLE(deinit)
#endif /* SP_MANGLE */
extern void SPCDECL deinit PROTOTYPE((SPAPI_ARG_PROTO_DECL int));
#ifdef __cplusplus
}
#endif

#ifndef SP_CONTEXT_SWITCH_HOOK
#define SP_CONTEXT_SWITCH_HOOK sp_context_switch_hook_python
#endif

#ifdef __cplusplus
extern "C" {
#endif
/* Used when SP_SINGLE_THREADED is true. You have to define it in your
   foreign code.  Will be called with 1 when any procedure in the
   foreign resource is called by a SICStus run-time. Will be called
   with 0 right before returning to the SICStus run-time. It is
   allowed to call the SICStus API. This hook can be used to switch
   the global state (using SP_foreign_stash()).
*/
extern void SPCDECL SP_CONTEXT_SWITCH_HOOK (int);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
extern SPGLUEEXP SP_MainFun sp_main_SPENV_python;
#ifdef __cplusplus
}
#endif
static int SPCDECL python_init_stub(GlueArgdecl, int when)
   {
  int glue_retval = 1;
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
   SP_STUB_SETUP_API(python)

  glue_flidata->excp_flag = 1;
  init(SPAPI_ARG when);

  GlueTestExcp;
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
}
static int SPCDECL python_deinit_stub(GlueArgdecl, int when)
   {
  int glue_retval = 1;
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
   SP_STUB_SETUP_API(python)

  glue_flidata->excp_flag = 1;
  deinit(SPAPI_ARG when);

  GlueTestExcp;
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
}


#ifdef __cplusplus
extern "C" {
#endif
/* 3.9 Mangle the name for link-time checking of MULTI_SP_AWARE-ness etc */
#ifdef SP_MANGLE
#define python_exec SP_MANGLE(python_exec)
#endif /* SP_MANGLE */
extern void SPCDECL python_exec PROTOTYPE((
    SPAPI_ARG_PROTO_DECL
    SP_term_ref));
#ifdef __cplusplus
}
#endif
static int SPCDECL python_stub_0(GlueArgdecl)
{
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_term_ref glue_ix;
  int glue_retval = 1;
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
  SP_STUB_SETUP_API(python)

  glue_ix = SP_new_term_refs(1);
  glue_flidata->excp_flag = 1;
  GlueRefTerm(glue_ix+0) = GlueX(0);
  python_exec(SPAPI_ARG
glue_ix+0);
  GlueTestExcp;
  SP_reset_term_refs(glue_ix);
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
}



#ifdef __cplusplus
extern "C" {
#endif
/* 3.9 Mangle the name for link-time checking of MULTI_SP_AWARE-ness etc */
#ifdef SP_MANGLE
#define python_set SP_MANGLE(python_set)
#endif /* SP_MANGLE */
extern void SPCDECL python_set PROTOTYPE((
    SPAPI_ARG_PROTO_DECL
    SP_term_ref,
    SP_term_ref));
#ifdef __cplusplus
}
#endif
static int SPCDECL python_stub_1(GlueArgdecl)
{
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_term_ref glue_ix;
  int glue_retval = 1;
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
  SP_STUB_SETUP_API(python)

  glue_ix = SP_new_term_refs(2);
  glue_flidata->excp_flag = 1;
  GlueRefTerm(glue_ix+0) = GlueX(0);
  GlueRefTerm(glue_ix+1) = GlueX(1);
  python_set(SPAPI_ARG
glue_ix+0, glue_ix+1);
  GlueTestExcp;
  SP_reset_term_refs(glue_ix);
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
}



#ifdef __cplusplus
extern "C" {
#endif
/* 3.9 Mangle the name for link-time checking of MULTI_SP_AWARE-ness etc */
#ifdef SP_MANGLE
#define python_eval SP_MANGLE(python_eval)
#endif /* SP_MANGLE */
extern void SPCDECL python_eval PROTOTYPE((
    SPAPI_ARG_PROTO_DECL
    SP_term_ref,
    SP_term_ref));
#ifdef __cplusplus
}
#endif
static int SPCDECL python_stub_2(GlueArgdecl)
{
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_term_ref glue_ix;
  int glue_retval = 1;
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
  SP_STUB_SETUP_API(python)

  glue_ix = SP_new_term_refs(3);
  glue_flidata->excp_flag = 1;
  GlueRefTerm(glue_ix+0) = GlueX(0);
  GlueRefTerm(glue_ix+1) = GlueX(1);
  python_eval(SPAPI_ARG
glue_ix+0, glue_ix+2);
  GlueSkipArgsOnExcp;
  if(!SP_unify(glue_ix+1,glue_ix+2)) goto glue_fail;
 glue_way_out:
  GlueTestExcp;
  SP_reset_term_refs(glue_ix);
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
 glue_fail:
  glue_retval=0;
  goto glue_way_out;
}



#ifdef __cplusplus
extern "C" {
#endif
/* 3.9 Mangle the name for link-time checking of MULTI_SP_AWARE-ness etc */
#ifdef SP_MANGLE
#define python_call SP_MANGLE(python_call)
#endif /* SP_MANGLE */
extern void SPCDECL python_call PROTOTYPE((
    SPAPI_ARG_PROTO_DECL
    SP_term_ref,
    SP_term_ref,
    SP_term_ref));
#ifdef __cplusplus
}
#endif
static int SPCDECL python_stub_3(GlueArgdecl)
{
  register struct sp_fli_info *glue_flidata = GetGlueFLIData();
  SP_term_ref glue_ix;
  int glue_retval = 1;
  SP_STUB_LOCAL_DECLARATIONS(python);

  /* End of local variables */

  {
  SP_STUB_SETUP_API(python)

  glue_ix = SP_new_term_refs(4);
  glue_flidata->excp_flag = 1;
  GlueRefTerm(glue_ix+0) = GlueX(0);
  GlueRefTerm(glue_ix+1) = GlueX(1);
  GlueRefTerm(glue_ix+2) = GlueX(2);
  python_call(SPAPI_ARG
glue_ix+0, glue_ix+1, glue_ix+3);
  GlueSkipArgsOnExcp;
  if(!SP_unify(glue_ix+2,glue_ix+3)) goto glue_fail;
 glue_way_out:
  GlueTestExcp;
  SP_reset_term_refs(glue_ix);
  SP_MAYBE_UNLOCK_SINGLE_THREADED_RESOURCE(python);
  }
  return glue_retval;
 glue_fail:
  glue_retval=0;
  goto glue_way_out;
}

static SP_GlueFun *python_funcs[] = {
	python_stub_0,
	python_stub_1,
	python_stub_2,
	python_stub_3,
0};
static const char *python_prednames[] = {
	"exec",
	"set",
	"eval",
	"call",
0};
static int python_arities[] = {
	1,
	2,
	2,
	3,
-1};


SPGLUEEXP1 int SPGLUEEXP2 SPCDECL sp_main_SPENV_python(SP_MAINFUN_PARAMS *params)
{
   int res;
#if MULTI_SP_AWARE
   SPAPI_ARG_LOCAL_DECL
#endif /* MULTI_SP_AWARE */
   res=sp_main_helper(params, 131073, GetSICStusDISPATCHAddress(), &sp_resource_mutex_python,python_funcs, python_prednames, python_arities, python_init_stub, python_deinit_stub);
   if (res != 0)   {
      /* version mismatch or other API error */
      return res;
   }
#if SICSTUS_API_STRUCT_DBG_MEMBERS
  {
     params->spenv->mainfunc = (SP_MainFun *)getglueflidata;
  }
#endif /* SICSTUS_API_STRUCT_DBG_MEMBERS */
  return res;
}

